"""empty message

Revision ID: 3009d82ceca0
Revises: 86c1f8680c92
Create Date: 2020-07-22 13:39:07.783629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3009d82ceca0'
down_revision = '86c1f8680c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('q_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'queries', 'query_types', ['q_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_column('queries', 'q_type')
    # ### end Alembic commands ###
