"""split out date and time

Revision ID: 9979831ae7ea
Revises: c0bbad40f39f
Create Date: 2020-07-24 12:26:44.643169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9979831ae7ea'
down_revision = 'c0bbad40f39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q_type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('q_type')
    )
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q_type', sa.Integer(), nullable=True),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('time', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('referral', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['q_type'], ['query_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queries')
    op.drop_table('query_types')
    # ### end Alembic commands ###
