"""empty message

Revision ID: c0bbad40f39f
Revises: 3009d82ceca0
Create Date: 2020-07-24 12:25:03.693180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bbad40f39f'
down_revision = '3009d82ceca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('date', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'queries', 'query_types', ['q_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_column('queries', 'date')
    # ### end Alembic commands ###
